#!/usr/bin/env bash
input=$1
pandoc -f markdown_github+tex_math_dollars+inline_code_attributes+header_attributes+auto_identifiers+startnum+definition_lists-ascii_identifiers+fancy_lists+fenced_code_attributes+markdown_in_html_blocks+simple_tables+subscript+superscript  -t revealjs  -s --template=my.slidercss --slide-level=1 -i --email-obfuscation=references --katex -o ${input%.*}.html $input
